// ─── Premium Engine — Authored Script Data ───────────────────────────────────
// Hand-authored. NOT generated by the baseline Python pipeline.
//
// This file holds two sets:
//   - premiumVideos (legacy scaffold, PremiumVideoSpec): scaffold
//     composition "premium-test-01" reads from here.
//   - premiumHookVideos (new schema, PremiumVideo): real authored hooks
//     rendered via the end-to-end HookScene path. V12 lives here.

import type { PremiumVideoSpec, PremiumVideo } from './types-premium';

// ─── Legacy scaffold data (unchanged) ────────────────────────────────────────

const premiumTest01: PremiumVideoSpec = {
  totalFrames: 90,
  voiceSrc: '',
  scenes: [
    {
      id: 'scene-01',
      kind: 'hook',
      startFrame: 0,
      durationFrames: 90,
      text: 'Premium render path: scaffold check.',
      beats: [],
    },
  ],
};

export const premiumVideos: Record<string, PremiumVideoSpec> = {
  'premium-test-01': premiumTest01,
};

// ─── New schema data — V12 premium hook (end-to-end) ─────────────────────────
// Matches AUTHORING_MODEL §4 reference example. Slice scope:
//   - evidence: data_point
//   - annotation: bracket
//   - one scene only (hook)
//
// Voice is intentionally left empty for the scaffold render. A real voice
// file can be wired later by flipping voice_src to 'v12.mp3' once the voice
// cue is re-recorded to match the premium hook timing.

const v12PremiumHook: PremiumVideo = {
  video_id: 'v12-premium',
  total_frames: 150,          // 5s at 30fps — enough for evidence, bracket, caption
  fps: 30,
  voice_src: '',              // empty for scaffold; wire later
  rail: {
    channel: 'DIAG',
    show_timestamp: true,
    show_signal_indicator: true,
  },
  scenes: [
    {
      scene_id: 'v12-premium-hook-01',
      scene_kind: 'hook',
      rail_tag: 'pH 01',
      timing: {
        start_frame: 0,
        duration_frames: 150,
        voice_window: { start_frame: 8, end_frame: 140 },
      },
      evidence: {
        type: 'data_point',
        ref_id: 'ref. 07',
        value: '1.8',
        unit_label: 'pH',
        range_label: 'normal: 1.5–3.5',
        emphasis: 'normal',
      },
      annotation: {
        gesture: 'bracket',
        fire_on_word: 'reputation',
        label: 'within normal range',
      },
      caption: {
        text: 'Stomach acid gets a bad reputation.',
        anchor: 'Stomach acid gets',
        accent_word: 'reputation',
      },
    },
  ],
};

export const premiumHookVideos: Record<string, PremiumVideo> = {
  'v12-premium': v12PremiumHook,
};
