// Auto-generated by automation/steps/06_render.py
// Maria can edit this file by hand, but tile entries should be written
// by the automation pipeline (step 04_align_tiles.py).
import { PhraseSpec } from './types';

export const batch5Videos: Record<string, { totalFrames: number; phrases: PhraseSpec[] }> = {
  // entries inserted by render step
  v13: {
    totalFrames: 3280,
    phrases: [
      { startFrame: 2891, durationFrames: 193, text: "People spend thousands getting. Tile. Body one. Anchor. A" },
      { startFrame: 3085, durationFrames: 148, text: "malgum fillings are roughly. Tile. CTA. Anchor." },
      { startFrame: 3232, durationFrames: 34, text: "Link in bio." }
    ]
  },

  v14: {
    totalFrames: 3391,
    phrases: [
      { startFrame: 3011, durationFrames: 179, text: "gets classified alongside tobacco. Tile. Body honor one. Anchor." },
      { startFrame: 3205, durationFrames: 140, text: "The IRC puts AFLA talks in. Tile CTA. Anchor." },
      { startFrame: 3350, durationFrames: 30, text: "Link in bio." }
    ]
  },

};
