// Auto-generated by automation/steps/06_render.py
// Maria can edit this file by hand, but tile entries should be written
// by the automation pipeline (step 04_align_tiles.py).
import { PhraseSpec } from './types';

export const batch5Videos: Record<string, { totalFrames: number; phrases: PhraseSpec[] }> = {
  v12: {
    totalFrames: 1723,
    phrases: [
      { startFrame: 0, durationFrames: 58, text: "Stomach acid gets a bad reputation.", backdrop: { kind: "editorial" } },
      { startFrame: 82, durationFrames: 177, text: "But here's what actually happens with low acid: food sits in the stomach too long, ferments, and generates pressure.", backdrop: { kind: "diagram" } },
      { startFrame: 276, durationFrames: 146, text: "That pressure forces whatever acid exists upward. The symptom is reflux.", backdrop: { kind: "diagram" } },
      { startFrame: 449, durationFrames: 113, text: "The instinct is to suppress acid further. Wrong direction.", backdrop: { kind: "diagram" } },
      { startFrame: 601, durationFrames: 110, text: "When acid is already insufficient, suppression deepens the dysfunction.", backdrop: { kind: "diagram" } },
      { startFrame: 733, durationFrames: 134, text: "The LES — the valve — needs an acid signal to close properly.", backdrop: { kind: "diagram" } },
      { startFrame: 866, durationFrames: 204, text: "No signal, valve stays loose. More reflux. It's a loop that PPIs sustain, not solve.", backdrop: { kind: "diagram" } },
      { startFrame: 1108, durationFrames: 226, text: "The pattern I observe: clients on long-term PPI therapy often have worse motility, more bloating, and incomplete protein digestion.", backdrop: { kind: "diagram" } },
      { startFrame: 1355, durationFrames: 122, text: "Because acid isn't the enemy. It's the signal the whole system runs on.", backdrop: { kind: "diagram" } },
      { startFrame: 1503, durationFrames: 194, text: "Weaning requires rebuilding acid capacity slowly, not suppressing it permanently. That sequence matters.", backdrop: { kind: "diagram" } },
      { startFrame: 1697, durationFrames: 30, text: "Link in bio", backdrop: { kind: "flat" } }
    ]
  },
  v13: {
    totalFrames: 1719,
    phrases: [
      { startFrame: 0, durationFrames: 358, text: "Mercury vapor releases continuously from amalgam fillings, chewing, heat, grinding, and they each one spikes exposure. So the instinct is remove them immediately. That instinct is wrong." },
      { startFrame: 383, durationFrames: 816, text: "Here's the mechanism. Amalgam removal is a high exposure event. During the procedure, mercury vapor concentrations spike sharply, even with protective protocols. If your detox pathways, liver phase two, bile flow, lymphatic drainage, aren't functional before that event, the mobilized mercury has nowhere to go. It redistributes. Tissues absorb it faster than the body can clear it. Symptoms worsen, not improve." },
      { startFrame: 1250, durationFrames: 341, text: "The pattern I keep seeing, people who removed amalgams first report feeling worse for months, the ones who opened drainage pathways supported kidney and liver function and then removed. Those cases move differently." },
      { startFrame: 1610, durationFrames: 85, text: "Removal isn't the question. Readiness is Lincoln" },
      { startFrame: 1694, durationFrames: 30, text: "Link in bio" }
    ]
  },
  v14: {
    totalFrames: 1708,
    phrases: [
      { startFrame: 11, durationFrames: 433, text: "Tox is produced by Aspergillus mold, IARC Group 1 carcinogen. Same classification as tobacco, not a fringe concern. One of the most researched mycotoxins in existence," },
      { startFrame: 460, durationFrames: 1222, text: "here's what makes it different from the mold conversation most people are having. This isn't about water damage buildings, it's about food, corn, peanuts, tree nuts, dried spices, grains, stored improperly, Aspergillus moves in. The toxin is colorless, odorless, heat stable. Cooking doesn't eliminate it, the primary target is the liver, the organ processing everything you're trying to use to recover. When liver burden is high and detox keeps stalling, afela Tox in exposure is almost never on the checklist, not because it's rare, because nobody thinks to look at the pantry. That's the" },
      { startFrame: 1682, durationFrames: 30, text: "Link in bio" }
    ]
  },
};
