// Auto-generated by automation/steps/06_render.py
// Maria can edit this file by hand, but tile entries should be written
// by the automation pipeline (step 04_align_tiles.py).
import { PhraseSpec } from './types';

export const batch5Videos: Record<string, { totalFrames: number; phrases: PhraseSpec[] }> = {
  v12: {
    totalFrames: 1734,
    phrases: [
      { startFrame: 0, durationFrames: 48, text: "Stomach acid gets a bad reputation." },
      { startFrame: 63, durationFrames: 166, text: "But here's what actually happens with low acid: food sits in the stomach too long, ferments, and generates pressure." },
      { startFrame: 252, durationFrames: 147, text: "That pressure forces whatever acid exists upward. The symptom is reflux." },
      { startFrame: 409, durationFrames: 119, text: "The instinct is to suppress acid further. Wrong direction." },
      { startFrame: 566, durationFrames: 113, text: "When acid is already insufficient, suppression deepens the dysfunction." },
      { startFrame: 709, durationFrames: 127, text: "The LES — the valve — needs an acid signal to close properly." },
      { startFrame: 853, durationFrames: 200, text: "No signal, valve stays loose. More reflux. It's a loop that PPIs sustain, not solve." },
      { startFrame: 1091, durationFrames: 237, text: "The pattern I observe: clients on long-term PPI therapy often have worse motility, more bloating, and incomplete protein digestion." },
      { startFrame: 1361, durationFrames: 118, text: "Because acid isn't the enemy. It's the signal the whole system runs on." },
      { startFrame: 1508, durationFrames: 201, text: "Weaning requires rebuilding acid capacity slowly, not suppressing it permanently. That sequence matters." },
      { startFrame: 1709, durationFrames: 30, text: "Link in bio" }
    ]
  },
  v13: {
    totalFrames: 1800,
    phrases: [
      { startFrame: 0, durationFrames: 379, text: "Mercury vapor releases continuously from amalgam fillings, chewing, heat, grinding, the each one spikes exposure. So the instinct is remove them immediately. That instinct is wrong." },
      { startFrame: 403, durationFrames: 856, text: "Here's the mechanism. Amalgam removal is a high exposure event. During the procedure, mercury vapor concentration spike sharply, even with protective protocols. If your detox pathways, liver phase to bile flow, lymphatic drainage, aren't functional before that event, the mobilized mercury has nowhere to go. It redistributes. Tissues absorb it faster than the body can clear it. Symptoms worsen, not improve." },
      { startFrame: 1301, durationFrames: 332, text: "The pattern I keep seeing, people who removed amalgams first report feeling worse for months. The ones who opened drainage pathways supported kidney and liver function and then removed, those cases moved differently." },
      { startFrame: 1652, durationFrames: 78, text: "Removal isn't the question. Readiness is." },
      { startFrame: 1757, durationFrames: 30, text: "Link in bio." }
    ]
  },
  v14: {
    totalFrames: 3509,
    phrases: [
      { startFrame: 3002, durationFrames: 314, text: "The IAR classifies AF -LA Tox in tile, body I -1. Anchor" },
      { startFrame: 3317, durationFrames: 146, text: "is produced by Aspergillus, tile, CTA, anchor," },
      { startFrame: 3469, durationFrames: 30, text: "link in bio." }
    ]
  },
};
